{
 "title": "Blinkenlights",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "Pool", "label": "Select queue", "query": "jobs_submitted_total" },
   { "name": "Customer", "label": "Select customer", "query": "jobs_submitted_total" }
  ]
 },
 "panels": [
  {
   "title": "Current jobs queued",
   "type": "singlestat",
   "description": "Current total number of jobs in queue",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(job_queue_current{poolName=~\"${Pool}\", customer=~\"${Customer}\"})"
    }
   ]
  },
  {
   "title": "Avg. queue time",
   "type": "singlestat",
   "description": "Average time a job spent in queue in selected range",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(max_over_time(job_queue_duration_seconds{poolName=~\"${Pool}\",customer=~\"${Customer}\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Avg. job duration",
   "type": "singlestat",
   "description": "Average time taken to complete a job in selected range",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_duration_seconds{result=\"complete\",poolName=~\"${Pool}\",customer=~\"${Customer}\"})"
    }
   ]
  },
  {
   "title": "Job success %",
   "type": "singlestat",
   "description": "Jobs success percentage in selected range",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jobs_completed_total{poolName=~\"$Pool\",customer=~\"${Customer}\"}[$__range]) or up * 0) / (sum(increase(jobs_failed_total{poolName=~\"$Pool\",customer=~\"${Customer}\"}[$__range]) or up * 0) + sum(increase(jobs_completed_total{poolName=~\"$Pool\",customer=~\"${Customer}\"}[$__range]) or up * 0))"
    }
   ]
  },
  {
   "title": "Current jobs active",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(job_active_current{poolName=~\"${Pool}\", customer=~\"${Customer}\"})"
    }
   ]
  },
  {
   "title": "Jobs submitted",
   "type": "singlestat",
   "description": "Jobs submitted in selected range",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jobs_submitted_total{poolName=~\"${Pool}\",customer=~\"${Customer}\"}[$__range]) or up * 0)"
    }
   ]
  },
  {
   "title": "Max queue duration",
   "type": "singlestat",
   "description": "Longest time a job spent in queue in selected range",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(job_queue_duration_seconds{poolName=~\"${Pool}\",customer=~\"${Customer}\"})"
    }
   ]
  },
  {
   "title": "Max job duration",
   "type": "singlestat",
   "description": "Longest time a job took to execute in selected range",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(job_duration_seconds{poolName=~\"${Pool}\",customer=~\"${Customer}\"})"
    }
   ]
  },
  {
   "title": "Jobs completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jobs_completed_total{poolName=~\"${Pool}\", customer=~\"${Customer}\"}[$__range]) or up * 0)"
    }
   ]
  },
  {
   "title": "Jobs failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_total{poolName=~\"${Pool}\",customer=~\"${Customer}\"}[$__range]) or up * 0)"
    }
   ]
  },
  {
   "title": "Current servers active",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servers_active_current{poolName=~\"${Pool}\"}) / (sum(servers_active_current{poolName=~\"${Pool}\"}) + sum(servers_available_current{poolName=~\"${Pool}\"}) + sum(servers_unavailable_current{poolName=~\"${Pool}\"}))"
    }
   ]
  },
  {
   "title": "Server health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servers_active_current{poolName=~\"${Pool}\"} + servers_available_current{poolName=~\"${Pool}\"}) / sum(servers_available_current{poolName=~\"${Pool}\"} + servers_active_current{poolName=~\"${Pool}\"} + servers_unavailable_current{poolName=~\"${Pool}\"})"
    }
   ]
  },
  {
   "title": "Servers active %",
   "type": "graph",
   "description": "Percentage of servers active over selected range",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(servers_active_current{poolName=~\"${Pool}\"}) / (sum(servers_active_current{poolName=~\"${Pool}\"}) + sum(servers_available_current{poolName=~\"${Pool}\"}) + sum(servers_unavailable_current{poolName=~\"${Pool}\"}))",
     "legendFormat": "servers active"
    }
   ]
  },
  {
   "title": "Servers unavailable %",
   "type": "graph",
   "description": "Number of servers unavailable over selected range",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(servers_unavailable_current{poolName=~\"${Pool}\"}) / (sum(servers_active_current{poolName=~\"${Pool}\"}) + sum(servers_available_current{poolName=~\"${Pool}\"}) + sum(servers_unavailable_current{poolName=~\"${Pool}\"}))",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Servers idle",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servers_available_current{poolName=~\"${Pool}\"})"
    }
   ]
  },
  {
   "title": "Servers total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(servers_unavailable_current{poolName=~\"${Pool}\"}) + sum(servers_active_current{poolName=~\"${Pool}\"}) + sum(servers_available_current{poolName=~\"${Pool}\"})"
    }
   ]
  },
  {
   "title": "Max job duration by customer",
   "type": "grafana-piechart-panel",
   "description": "Longest job duration by customer in selected range",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(job_duration_seconds{poolName=~\"$Pool\"}[$__range])) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Jobs completed by customer",
   "type": "grafana-piechart-panel",
   "description": "Number of jobs completed by customer in selected range",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jobs_completed_total{poolName=~\"$Pool\"}[$__range])) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Jobs failed by customer",
   "type": "grafana-piechart-panel",
   "description": "Jobs failed by customer in selected range",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jobs_failed_total{poolName=~\"${Pool}\"}[$__range]) or up * 0) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Avg. Queue time by Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(job_queue_duration_seconds{customer=~\"${Customer}\"}[$__interval])) by (poolName)",
     "legendFormat": "{{poolName}}"
    }
   ]
  },
  {
   "title": "Avg. Job duration by Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(avg_over_time(job_duration_seconds{customer=~\"${Customer}\"}[$__interval])) by (poolName)",
     "legendFormat": "{{poolName}}"
    }
   ]
  },
  {
   "title": "Jobs submitted per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jobs_submitted_total{poolName=~\"$Pool\",customer=~\"${Customer}\"}[$__interval]) or up * 0) * 60"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 34 },
   "content": "<h1 class=\"text-center\">title</h1>"
  }
 ]
}